version: "3.8"

#####
services:

## mysql
  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql/volumes:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=${TZ:-Asia/Taipei}
    ports:
      - "3306:3306"
    networks:
      - internal

## php-fpm
  php-fpm:
    build: ./php-fpm
    volumes:
      - ../demo:/var/www/html
    networks:
      - internal

## webserver
  webserver:
    build: ./nginx
    working_dir: /var/www/html
    volumes:
      - ../demo:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal
    links:
      - php-fpm:links-php-fpm
    depends_on:
      - php-fpm

## adminer
  adminer:
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - 7777:8080
    networks:
      - internal
    restart: always

#####
networks:
  internal:
    name: ${NETWORKS:-internal}
    driver: bridge